# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "aea-paper"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Gatlen Culp"]
license = "Unlicense"
description = "American Economics Association paper template. Minimally implemented, not ready for submission or official, but felt worth sharing as a starting point regardless. Derived from IEEE-Charged template."
homepage = "https://github.com/GatlenCulp/typst-aea-paper"
repository = "https://github.com/GatlenCulp/typst-aea-paper"
keywords = ["economics"]
categories = ["paper"]
disciplines = ["economics"]
# compiler = ""
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
